name: Terraform Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fmt:
    name: Format Terraform Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Terraform FMT step
      - name: Terraform FMT
        run: terraform fmt -check -recursive

  validate:
    name: Validate Terraform Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Terraform Validate step
      - name: Terraform Validate
        run: terraform validate

  build:
    name: Build Terraform Infrastructure
    runs-on: ubuntu-latest
    needs: [validate]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        
      # Terraform Plan step
      - name: Terraform Plan
        run: terraform plan -out=tfplan

  deploy:
    name: Deploy Terraform Infrastructure
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Set your AWS region here
        
      # Set environment variables from secrets
      - name: Set Terraform State Name
        run: echo "TF_STATE_NAME=${{ secrets.TF_STATE_NAME }}" >> $GITHUB_ENV

      # Apply the Terraform plan
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
