name: Terraform Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 4.18.0  # Specify the Terraform version you are using

      - name: Terraform Init
        run: terraform init

      - name: Terraform FMT Check
        run: terraform fmt -check -recursive

      - name: Terraform FMT Apply
        run: terraform fmt -recursive
        continue-on-error: true  # Ensures the workflow continues even if formatting changes are made

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

  deploy:
    name: Deploy Terraform Infrastructure
    runs-on: ubuntu-latest
    needs: [terraform]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
        
      - name: Set Terraform State Name
        run: echo "TF_STATE_NAME=${{ secrets.TF_STATE_NAME }}" >> $GITHUB_ENV

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
